repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        entry: black .
        types: [ python ]
        stages: [ commit ]
      - id: system
        name: isort
        entry: isort .
        pass_filenames: false
        language: system
        stages: [ commit ]
      - id: system
        name: MyPy
        entry: mypy src
        pass_filenames: false
        language: system
        stages: [ commit ]
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        stages: [ commit ]